---
name: Build & Push
on:
  workflow_call:
    inputs:
      dockerhub_user:
        required: true
        type: string
    secrets:
      dockerhub_token:
        required: true
permissions:
  contents: read
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Login to Dockerhub
        uses: docker/login-action@v4
        with:
          username: ${{ inputs.dockerhub_user }}
          password: ${{ secrets.dockerhub_token }}
      - name: Build and Push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile.Multistage
          push: true
          tags: |
            ${{ inputs.dockerhub_user }}/two-tier-flask-app:latest
            ${{ inputs.dockerhub_user }}/two-tier-flask-app:${{ github.sha }}
