---
name: Dependency Scan
on:
  workflow_call:
permissions:
  contents: read
  security-events: write
jobs:
  dependency-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run Dependency Scan
        uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          inputs: requirements.txt
