---
name: Deployment
on:
  workflow_call:
    secrets:
      ec2_host:
        required: true
      ec2_private_key:
        required: true
      ec2_user:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to Remote Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.ec2_host }}
          user: ${{ secrets.ec2_user }}
          key: ${{ secrets.ec2_private_key }}
          script: |
            echo "starting deployment..."
            mkdir -p flask-app
