---
name: DevSecOps Workflow
on:
  workflow_dispatch:
jobs:
  code-quality-check:
    uses: ./code-quality.yml
  secret-scan:
    uses: ./secret-scan.yml
  SAST:
    uses: ./SAST.yml
  dependency-scan:
    uses: ./dependency-scan.yml
  dockerfile-scan:
    uses: ./dockerfile-scan.yml
  build-and-push:
    uses: ./build-and-push.yml
  image-scan:
    uses: ./image-scan.yml
  deploy:
    uses: ./deploy.yml
