---
name: Dockerfile Scan
on:
  workflow_call:
permissions:
  contents: read
jobs:
  dockerfile-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Scan Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.Multistage
